interface ReadmeViewerProps {
	html: string;
	className?: string;
}

// Render the HTML generated by remark/rehype using the portfolio content styles
export function ReadmeViewer({ html, className = "" }: ReadmeViewerProps) {
	return (
		<div
			className={`readme-content font-roboto leading-relaxed ${className}`}
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}
