interface ReadmeViewerProps {
	html: string;
	className?: string;
}

// Render the HTML generated by remark/rehype using the portfolio content styles
export function ReadmeViewer({ html, className = "" }: ReadmeViewerProps) {
	return (
		<div
			className={`readme-content font-roboto leading-relaxed overflow-x-hidden min-w-0 w-full ${className}`}
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}
